### ISSUE TITLE
Line wrapping issue with silver in termite (using bash)

### ISSUE THREAD

**Issue by tobip** [reujab/silver#58]
I have following issue in my terminal:

![terminal](https://user-images.githubusercontent.com/3918330/92761832-55e3f900-f392-11ea-8f8b-964f82ac181b.gif)

I am running silver 1.1.0, termite 15, bash 5.0
(Manjaro ARM Sway on a Pinebook Pro)

I couldn't find any help searching the web. Do you have any advice?

**Comment by magistau** [comment]
1. Does that happen without `silver`?
1. Does that happen in other terminal emulators?
1. Does that happen with other shells?
1. Please attach your config

**Comment by faokryn** [comment]
I have observed this behavior with the Sakura terminal emulator on Fedora 32

The relevant portion of my `.bashrc`:
``` sh
if which silver &> /dev/null; then
    SILVER=(env:white:black:USER dir:blue:white git:green:white status:red:white)
    home_icon=$'\uf7db'
    export SILVER_SHELL=$0
    export SILVER_ICONS=nerd
    export SILVER_DIR_ALIASES="$HOME:$home_icon "
    eval "$(silver init)"
fi
```

**Comment by magistau** [comment]
> I have observed this behavior with the Sakura terminal emulator on Fedora 32
> 
> The relevant portion of my `.bashrc`:
> 
> ```shell
> if which silver &> /dev/null; then
>     SILVER=(env:white:black:USER dir:blue:white git:green:white status:red:white)
>     home_icon=$'\uf7db'
>     export SILVER_SHELL=$0
>     export SILVER_ICONS=nerd
>     export SILVER_DIR_ALIASES="$HOME:$home_icon "
>     eval "$(silver init)"
> fi
> ```

Can't reproduce neither with latest crates.io release nor git version, Alacritty, Arch Linux

**Comment by tobip** [comment]
The relevant part in my `.bashrc` seems to be

```
SILVER=(status:black:white user:yellow:black dir:blue:black git:green:black cmdtime:magenta:black)
export SILVER_ICONS=nerd
export SILVER_SHELL=$0 # bash, zsh, or fish
eval "$(silver init)"
```

After commenting out these lines the line wrapping works like intended.

**Comment by magistau** [comment]
Does it reproduce on the git version?
To use it:

1. Remove all `SILVER*` environment variables, leave only `source <(silver init)` or `eval "$(silver init)"` line
1. Create `~/.config/silver/silver.toml` with the following contents:

    ```toml
    [[left]]
    name = "status"
    color.background = "black"
    color.foreground = "white"

    [[left]]
    name = "user"
    color.background = "yellow"
    color.foreground = "black"

    [[left]]
    name = "dir"
    color.background = "blue"
    color.foreground = "black"

    [[left]]
    name = "git"
    color.background = "green"
    color.foreground = "black"

    [[left]]
    name = "cmdtime"
    color.background = "magenta"
    color.foreground = "black"
    ```

1. `cargo install --git https://github.com/reujab/silver`
1. Restart bash
