### ISSUE TITLE
Right prompt for shells not supporting it (bash, ion, powershell)

### ISSUE THREAD

**Issue by fdncred** [reujab/silver#64]
I now have `silver` working (kind of) on windows but only the left side seems to work. 

![image](https://user-images.githubusercontent.com/343840/97604314-546e9e80-19db-11eb-863d-1904b61eb1b7.png)

Here's the toml I'm using
```toml
[[left]]
name = "dir"
color.background = "blue"
color.foreground = "white"

[[left]]
name = "git"
color.background = "green"
color.foreground = "black"

[[right]]
name = "status"
color.background = "white"
color.foreground = "black"

[[right]]
name = "cmdtime"
color.background = "magenta"
color.foreground = "black"

[[right]]
name = "shell"
color.background = "green"
color.foreground = "black"
```

You can see in the screenshot that I changed the toml from black foreground to white just to see if it was seeing my toml file properly and it seems to be. Any ideas where to start with this?
